export const defaultPlayers = [
  { name: "Virat Kohli", nationality: "IND", role: "Batter", team: "RCB", base_price: 2.0 },
  { name: "Jasprit Bumrah", nationality: "IND", role: "Bowler", team: "MI", base_price: 2.0 },
  { name: "Rashid Khan", nationality: "AFG", role: "Bowler", team: "GT", base_price: 2.0 },
  { name: "Jos Buttler", nationality: "ENG", role: "WK-Batter", team: "RR", base_price: 2.0 },
  { name: "Glenn Maxwell", nationality: "AUS", role: "All-rounder", team: "RCB", base_price: 1.5 },
  { name: "Hardik Pandya", nationality: "IND", role: "All-rounder", team: "MI", base_price: 2.0 },
  { name: "Rishabh Pant", nationality: "IND", role: "WK-Batter", team: "DC", base_price: 2.0 },
  { name: "Pat Cummins", nationality: "AUS", role: "Bowler", team: "SRH", base_price: 2.0 },
  { name: "Shubman Gill", nationality: "IND", role: "Batter", team: "GT", base_price: 2.0 },
  { name: "Suryakumar Yadav", nationality: "IND", role: "Batter", team: "MI", base_price: 2.0 },
  { name: "Ravindra Jadeja", nationality: "IND", role: "All-rounder", team: "CSK", base_price: 2.0 },
  { name: "Quinton de Kock", nationality: "SA", role: "WK-Batter", team: "LSG", base_price: 1.5 },
  { name: "Trent Boult", nationality: "NZ", role: "Bowler", team: "RR", base_price: 1.5 },
  { name: "Mitchell Starc", nationality: "AUS", role: "Bowler", team: "KKR", base_price: 2.0 },
  { name: "Shreyas Iyer", nationality: "IND", role: "Batter", team: "KKR", base_price: 2.0 },
  { name: "KL Rahul", nationality: "IND", role: "WK-Batter", team: "LSG", base_price: 2.0 },
  { name: "Sam Curran", nationality: "ENG", role: "All-rounder", team: "PBKS", base_price: 1.5 },
  { name: "Mohammed Shami", nationality: "IND", role: "Bowler", team: "GT", base_price: 1.5 },
  { name: "Yuzvendra Chahal", nationality: "IND", role: "Bowler", team: "RR", base_price: 1.0 },
  { name: "David Warner", nationality: "AUS", role: "Batter", team: "DC", base_price: 1.5 },
];
